### ISSUE TITLE
Add ypcat as dependency

### ISSUE THREAD

**Issue by spreiter** [zimfw/completion#19]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

On EL8 `ypcat` is not installed by default. Can this be added to some requirements in the readme or checked during installation?

Related to #6

### Steps to reproduce

Using completion on hostnames failed with a message that `ypcat` is not installed.

### Current behavior

failure message and one has to abort the completion process entirely.

### Expected behavior

Warn during installation that ypcat is required

### zimfw info

```shell
zimfw version:        1.13.0 (built at 2024-02-17 02:05:06 UTC, previous commit is 9de3984)
LANG:                 en_US.UTF-8
OSTYPE:               linux-gnu
TERM:                 xterm-256color
TERM_PROGRAM:         
TERM_PROGRAM_VERSION: 
ZIM_HOME:             /home/sreiter/.zim
ZSH_VERSION:          5.5.1
```

**Comment by ericbn** [comment]
Hi @spreiter. `ypcat` is not installed in macOS either, and maybe in other OSes too. The command is `ypcat hosts 2>/dev/null` so it should fail silently if the `ypcat` command is not found. I wonder why are you seeing an error and why does the completion fail.

**Comment by spreiter** [comment]
Maybe this is a system related issue. In the example below I pressed TAB after `ssh wo`
```
> ssh woInstall package 'yp-tools' to provide command 'ypcat'? [N/y]
```

OK, seems to be related to the [PackageKitCommandNotFound](https://fedoraproject.org/wiki/Features/PackageKitCommandNotFound) package.

But after the question is raised, even pressing `n` does not return to my previous input and I have to abort with Ctrl-C.

**Comment by ericbn** [comment]
Thanks for detailing the error you're getting. I think the solution here is to test if ypcat is an available command before calling it. I'll update the script.

**Comment by spreiter** [comment]
Elegant solution. Thanks! ❤️
