### ISSUE TITLE
completion was already initialized message coming from /completion/init.zsh

### ISSUE THREAD

**Issue by FuzzOli87** [zimfw/completion#22]
### Prerequisites

- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

I've followed the instruction to deal with this bug but it feels broken since now it's saying the module calling it is the completion module itself. I checked all my files and can't find what could be triggering this.

### Steps to reproduce

Open up a terminal.

### Current behavior

I get this message on each new terminal instance:

```
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /Users/tsunade/.zim/modules/completion/init.zsh:35
```

### Expected behavior

Nothing shows

### zimfw info

zimfw version:        1.13.1 (built at 2024-04-28 19:07:19 UTC, previous commit is c86223f)
LANG:                 en_US.UTF-8
LC_TERMINAL_VERSION:  3.5.0
LC_TERMINAL:          iTerm2
OSTYPE:               darwin23.0
TERM:                 xterm-256color
TERM_PROGRAM:         iTerm.app
TERM_PROGRAM_VERSION: 3.5.0
ZIM_HOME:             /Users/tsunade/.zim
ZSH_VERSION:          5.9

**Comment by ericbn** [comment]
This in a new warning we’ve added for better clarity wherever compinit is called more than once, which should not happen, but it’s beyond Zim’s control. 

See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working

**Comment by FuzzOli87** [comment]
@ericbn Thanks for the prompt reply! My confusion is that the message is stating that it's happening within the `completion` module...unless something *else* is calling it but it's not really telling me who. 🤔

**Comment by ericbn** [comment]
Looks like your `${ZIM_HOME}/init.zsh` script in being sourced twice.

**Comment by FuzzOli87** [comment]
💩 Dang, I see it now. 😢 Thanks!!
